In [1]:
import os
import glob
import pandas as pd
from PIL import Image
path = "F:/PlateDetect/G+A_DATASET/platesonly"
os.chdir(path)
extension = 'jpg'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
all_filenames

['img_1.jpg',
 'img_10.jpg',
 'img_100.jpg',
 'img_1000.jpg',
 'img_1001.jpg',
 'img_1002.jpg',
 'img_1003.jpg',
 'img_1004.jpg',
 'img_1005.jpg',
 'img_1006.jpg',
 'img_1007.jpg',
 'img_1008.jpg',
 'img_1009.jpg',
 'img_101.jpg',
 'img_1010.jpg',
 'img_1011.jpg',
 'img_1012.jpg',
 'img_1013.jpg',
 'img_1014.jpg',
 'img_1015.jpg',
 'img_1016.jpg',
 'img_1017.jpg',
 'img_1018.jpg',
 'img_1019.jpg',
 'img_102.jpg',
 'img_1020.jpg',
 'img_1021.jpg',
 'img_1022.jpg',
 'img_1023.jpg',
 'img_1024.jpg',
 'img_1025.jpg',
 'img_1026.jpg',
 'img_1027.jpg',
 'img_1028.jpg',
 'img_1029.jpg',
 'img_103.jpg',
 'img_1030.jpg',
 'img_1031.jpg',
 'img_1032.jpg',
 'img_1033.jpg',
 'img_1034.jpg',
 'img_1035.jpg',
 'img_1036.jpg',
 'img_1037.jpg',
 'img_1038.jpg',
 'img_1039.jpg',
 'img_104.jpg',
 'img_1040.jpg',
 'img_1041.jpg',
 'img_1042.jpg',
 'img_1043.jpg',
 'img_1044.jpg',
 'img_1045.jpg',
 'img_1046.jpg',
 'img_1047.jpg',
 'img_1048.jpg',
 'img_1049.jpg',
 'img_105.jpg',
 'img_1050.jpg',
 'img_10

In [2]:
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
import numpy as np

lis  = []
for fn in all_filenames:
    img = load_img(fn)  # this is a PIL image
    x = img_to_array(img)  # this is a Numpy array with shape (3, 150, 150)
    #x = x.reshape((1,) + x.shape)
    lis.append(x)
    img.close()
    
lis

Using TensorFlow backend.


[array([[[ 162.,  176.,  179.],
         [ 162.,  176.,  179.],
         [ 163.,  177.,  180.],
         ..., 
         [ 174.,  179.,  185.],
         [ 177.,  182.,  188.],
         [ 179.,  184.,  190.]],
 
        [[ 174.,  188.,  191.],
         [ 174.,  188.,  191.],
         [ 175.,  189.,  192.],
         ..., 
         [ 172.,  177.,  183.],
         [ 173.,  178.,  184.],
         [ 172.,  177.,  183.]],
 
        [[ 192.,  203.,  207.],
         [ 192.,  203.,  207.],
         [ 193.,  204.,  208.],
         ..., 
         [ 175.,  180.,  184.],
         [ 174.,  179.,  183.],
         [ 172.,  177.,  181.]],
 
        ..., 
        [[  31.,   41.,   50.],
         [  30.,   40.,   49.],
         [  30.,   40.,   49.],
         ..., 
         [  33.,   37.,   48.],
         [  37.,   41.,   52.],
         [  40.,   44.,   55.]],
 
        [[  28.,   38.,   47.],
         [  28.,   38.,   47.],
         [  28.,   38.,   47.],
         ..., 
         [  57.,   62.,   66.],
   

In [3]:
path = "F:/PlateDetect/G+A_DATASET/platesonly/preview"
os.chdir(path)
extension = 'jpg'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
all_filenames

['cat_0_135.jpg',
 'cat_0_3220.jpg',
 'cat_0_3907.jpg',
 'cat_0_4280.jpg',
 'cat_0_5684.jpg',
 'cat_0_878.jpg',
 'cat_0_9.jpg',
 'cat_0_9530.jpg',
 'cat_0_983.jpg',
 'cat_100_2227.jpg',
 'cat_100_3744.jpg',
 'cat_100_4560.jpg',
 'cat_100_5059.jpg',
 'cat_100_5786.jpg',
 'cat_100_6326.jpg',
 'cat_100_7092.jpg',
 'cat_100_8988.jpg',
 'cat_100_9805.jpg',
 'cat_101_1310.jpg',
 'cat_101_1896.jpg',
 'cat_101_4149.jpg',
 'cat_101_4448.jpg',
 'cat_101_4879.jpg',
 'cat_101_6854.jpg',
 'cat_101_7008.jpg',
 'cat_101_9228.jpg',
 'cat_101_9410.jpg',
 'cat_102_1047.jpg',
 'cat_102_105.jpg',
 'cat_102_3564.jpg',
 'cat_102_4701.jpg',
 'cat_102_4765.jpg',
 'cat_102_541.jpg',
 'cat_102_7416.jpg',
 'cat_102_7878.jpg',
 'cat_102_8665.jpg',
 'cat_103_2421.jpg',
 'cat_103_3618.jpg',
 'cat_103_3860.jpg',
 'cat_103_4176.jpg',
 'cat_103_4321.jpg',
 'cat_103_4807.jpg',
 'cat_103_6247.jpg',
 'cat_103_6962.jpg',
 'cat_103_8686.jpg',
 'cat_104_1039.jpg',
 'cat_104_1433.jpg',
 'cat_104_1657.jpg',
 'cat_104_3030.jpg

In [4]:
for fn in all_filenames:
    img = load_img(fn)  # this is a PIL image
    x = img_to_array(img)  # this is a Numpy array with shape (3, 150, 150)
    #x = x.reshape((1,) + x.shape)
    lis.append(x)
    img.close()
len(lis)

10270

In [5]:
path = "F:/PlateDetect/G+A_DATASET/noplates"
os.chdir(path)
extension = 'jpg'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
all_filenames

['nimg_1.jpg',
 'nimg_10.jpg',
 'nimg_100.jpg',
 'nimg_1000.jpg',
 'nimg_1001.jpg',
 'nimg_1002.jpg',
 'nimg_1003.jpg',
 'nimg_1004.jpg',
 'nimg_1005.jpg',
 'nimg_1006.jpg',
 'nimg_1007.jpg',
 'nimg_1008.jpg',
 'nimg_1009.jpg',
 'nimg_101.jpg',
 'nimg_1010.jpg',
 'nimg_1011.jpg',
 'nimg_1012.jpg',
 'nimg_1013.jpg',
 'nimg_1014.jpg',
 'nimg_1015.jpg',
 'nimg_1016.jpg',
 'nimg_1017.jpg',
 'nimg_1018.jpg',
 'nimg_1019.jpg',
 'nimg_102.jpg',
 'nimg_1020.jpg',
 'nimg_1021.jpg',
 'nimg_1022.jpg',
 'nimg_1023.jpg',
 'nimg_1024.jpg',
 'nimg_1025.jpg',
 'nimg_1026.jpg',
 'nimg_1027.jpg',
 'nimg_1028.jpg',
 'nimg_1029.jpg',
 'nimg_103.jpg',
 'nimg_1030.jpg',
 'nimg_1031.jpg',
 'nimg_1032.jpg',
 'nimg_1033.jpg',
 'nimg_1034.jpg',
 'nimg_1035.jpg',
 'nimg_1036.jpg',
 'nimg_1037.jpg',
 'nimg_1038.jpg',
 'nimg_1039.jpg',
 'nimg_104.jpg',
 'nimg_1040.jpg',
 'nimg_1041.jpg',
 'nimg_1042.jpg',
 'nimg_1043.jpg',
 'nimg_1044.jpg',
 'nimg_1045.jpg',
 'nimg_1046.jpg',
 'nimg_1047.jpg',
 'nimg_1048.jpg',
 '

In [6]:

lisn  = []
for fn in all_filenames:
    img = load_img(fn)  # this is a PIL image
    x = img_to_array(img)  # this is a Numpy array with shape (3, 150, 150)
    #x = x.reshape((1,) + x.shape)
    lisn.append(x)
    img.close()
    
len(lisn)

9808

In [7]:
path = "F:/PlateDetect/noise"
os.chdir(path)
extension = 'jpg'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
all_filenames

['img_100_21.jpg',
 'img_100_22.jpg',
 'img_100_23.jpg',
 'img_100_24.jpg',
 'img_100_25.jpg',
 'img_100_26.jpg',
 'img_100_27.jpg',
 'img_100_28.jpg',
 'img_100_29.jpg',
 'img_100_30.jpg',
 'img_101_31.jpg',
 'img_101_32.jpg',
 'img_101_33.jpg',
 'img_101_34.jpg',
 'img_101_35.jpg',
 'img_101_36.jpg',
 'img_101_37.jpg',
 'img_101_38.jpg',
 'img_101_39.jpg',
 'img_101_40.jpg',
 'img_102_41.jpg',
 'img_102_42.jpg',
 'img_102_43.jpg',
 'img_102_44.jpg',
 'img_102_45.jpg',
 'img_102_46.jpg',
 'img_102_47.jpg',
 'img_102_48.jpg',
 'img_102_49.jpg',
 'img_102_50.jpg',
 'img_103_51.jpg',
 'img_103_52.jpg',
 'img_103_53.jpg',
 'img_103_54.jpg',
 'img_103_55.jpg',
 'img_103_56.jpg',
 'img_103_58.jpg',
 'img_103_59.jpg',
 'img_103_60.jpg',
 'img_104_61.jpg',
 'img_104_62.jpg',
 'img_104_63.jpg',
 'img_104_64.jpg',
 'img_104_65.jpg',
 'img_104_66.jpg',
 'img_104_67.jpg',
 'img_104_68.jpg',
 'img_104_69.jpg',
 'img_104_70.jpg',
 'img_105_71.jpg',
 'img_105_72.jpg',
 'img_105_73.jpg',
 'img_105_74

In [8]:
for fn in all_filenames:
    img = load_img(fn)  # this is a PIL image
    x = img_to_array(img)  # this is a Numpy array with shape (3, 150, 150)
    #x = x.reshape((1,) + x.shape)
    lisn.append(x)
    img.close()
    
len(lisn)

11809

In [9]:
path = "F:/PlateDetect/noise/preview"
os.chdir(path)
extension = 'jpg'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
all_filenames

['cat_0_2031.jpg',
 'cat_0_4194.jpg',
 'cat_1000_823.jpg',
 'cat_1000_8696.jpg',
 'cat_1001_6318.jpg',
 'cat_1001_9840.jpg',
 'cat_1002_4352.jpg',
 'cat_1002_9666.jpg',
 'cat_1003_4714.jpg',
 'cat_1003_5980.jpg',
 'cat_1004_5857.jpg',
 'cat_1004_8288.jpg',
 'cat_1005_1040.jpg',
 'cat_1005_1677.jpg',
 'cat_1006_1279.jpg',
 'cat_1006_3534.jpg',
 'cat_1007_2108.jpg',
 'cat_1007_5259.jpg',
 'cat_1008_3736.jpg',
 'cat_1008_418.jpg',
 'cat_1009_2328.jpg',
 'cat_1009_7566.jpg',
 'cat_100_5852.jpg',
 'cat_100_7222.jpg',
 'cat_1010_464.jpg',
 'cat_1010_5371.jpg',
 'cat_1011_4530.jpg',
 'cat_1011_6397.jpg',
 'cat_1012_6835.jpg',
 'cat_1012_8181.jpg',
 'cat_1013_1929.jpg',
 'cat_1013_5014.jpg',
 'cat_1014_7991.jpg',
 'cat_1014_9943.jpg',
 'cat_1015_4494.jpg',
 'cat_1015_944.jpg',
 'cat_1016_3934.jpg',
 'cat_1016_8548.jpg',
 'cat_1017_4739.jpg',
 'cat_1017_738.jpg',
 'cat_1018_8077.jpg',
 'cat_1018_9000.jpg',
 'cat_1019_6880.jpg',
 'cat_1019_7062.jpg',
 'cat_101_1423.jpg',
 'cat_101_1894.jpg',
 'c

In [10]:
for fn in all_filenames:
    img = load_img(fn)  # this is a PIL image
    x = img_to_array(img)  # this is a Numpy array with shape (3, 150, 150)
    #x = x.reshape((1,) + x.shape)
    lisn.append(x)
    img.close()
    
len(lisn)

15811

In [11]:
lisy = [1.0]*len(lis)
lisny = [0.0]*len(lisn)
lisy = lisy + lisny
lis = lis + lisn


In [7]:
import os
import glob
import pandas as pd
from PIL import Image
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
import numpy as np





datagen = ImageDataGenerator(
        rotation_range=3,
        width_shift_range=0.05,
        height_shift_range=0.05,
        shear_range=0.05,
        zoom_range=0.05,
        horizontal_flip=False,
        fill_mode='nearest')


i = 0
for batch in datagen.flow(np.array(lis), batch_size=1024,
                          save_to_dir='preview', save_prefix='cat', save_format='jpg'):
    i += 1
    if i > 3:
        break

In [22]:
len(lisy)

19144

In [12]:
lis = np.array(lis)
lisy = np.array(lisy)
print(lis.shape)
print(lisy.shape)

(26081, 50, 100, 3)
(26081,)


In [13]:
lis = lis/255.0


In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(lis, lisy, test_size=0.25)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

G:\Anaconda3\lib\site-packages\sklearn\utils\fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array


(19560, 50, 100, 3)
(19560,)
(6521, 50, 100, 3)
(6521,)


In [1]:
import os
import glob
import numpy as np
path = "F:/PlateDetect"
os.chdir(path)
lis = np.load('X_data.npy')
lisy = np.load('Y_data.npy')

In [3]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.layers import LeakyReLU
import tensorflow as tf
from keras.optimizers import SGD
from keras.callbacks import LearningRateScheduler


model = Sequential()

model.add(Conv2D(32, (3, 3), input_shape=(50, 100,3)   ))
#model.add(LeakyReLU(alpha=0.1))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2) ,strides = (2,2) ))
#model.add(Dropout(0.5))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2) ,strides = (2,2) ))
#model.add(Dropout(0.5))

model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2) ,strides = (2,2)  ))
#model.add(Dropout(0.5))


#model.add(Conv2D(64, (3, 3), activation='relu'))
#model.add(MaxPooling2D((2, 2) ,strides = (2,2)  ))
#model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(64))
#model.add(LeakyReLU(alpha=0.1))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
model.summary()

Using TensorFlow backend.


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 48, 98, 32)        896       
_________________________________________________________________
activation_1 (Activation)    (None, 48, 98, 32)        0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 24, 49, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 22, 47, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 11, 23, 64)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 9, 21, 128)        73856     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 4, 10, 128)        0         
__________

In [42]:
trnwts = np.array([1.0]*len(y_train))
trnwts[y_train == 0.0] = 2.0
trnwts

array([ 1.,  2.,  2., ...,  2.,  1.,  2.])

In [4]:
model.fit(X_train ,y_train , batch_size = 128 , epochs = 20 , validation_data = (X_test,y_test) )

Train on 19560 samples, validate on 6521 samples
Epoch 1/20
19560/19560 [==============================] - 83s 4ms/step - loss: 0.2274 - acc: 0.9090 - val_loss: 0.0345 - val_acc: 0.9908
Epoch 2/20
19560/19560 [==============================] - 57s 3ms/step - loss: 0.0462 - acc: 0.9876 - val_loss: 0.0199 - val_acc: 0.9956
Epoch 3/20
19560/19560 [==============================] - 57s 3ms/step - loss: 0.0278 - acc: 0.9930 - val_loss: 0.0174 - val_acc: 0.9969
Epoch 4/20
19560/19560 [==============================] - 57s 3ms/step - loss: 0.0212 - acc: 0.9950 - val_loss: 0.0147 - val_acc: 0.9974
Epoch 5/20
19560/19560 [==============================] - 57s 3ms/step - loss: 0.0230 - acc: 0.9960 - val_loss: 0.0247 - val_acc: 0.9951
Epoch 6/20
19560/19560 [==============================] - 57s 3ms/step - loss: 0.0182 - acc: 0.9958 - val_loss: 0.0157 - val_acc: 0.9980
Epoch 7/20
19560/19560 [==============================] - 57s 3ms/step - loss: 0.0206 - acc: 0.9968 - val_loss: 0.0555 - val_acc:

In [19]:
len(y_test[y_test == 1.0])

2584

In [45]:
y_pred = model.predict(X_test)

In [46]:
y_test[:10]

array([ 1.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.])

In [47]:
y_pred[:10]

array([[  1.00000000e+00],
       [  1.00000000e+00],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.00000000e+00],
       [  0.00000000e+00],
       [  1.00000000e+00],
       [  0.00000000e+00],
       [  6.33694371e-24],
       [  0.00000000e+00]], dtype=float32)

In [29]:
from keras.models import model_from_json

model_json = model.to_json()
with open("plate_detect_CNN.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("plate_detect_CNN_weights.h5")
print("Saved model to disk")

# later...
 


Saved model to disk


In [1]:
# load json and create model
from keras.models import model_from_json
import os
import glob
from PIL import Image
import numpy as np
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from matplotlib import image
from matplotlib import pyplot
path = "F:/PlateDetect"
os.chdir(path)
json_file = open('plate_detect_CNN.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("plate_detect_CNN_weights.h5")

Using TensorFlow backend.


In [55]:
yp_pred = loaded_model.predict(X_test[0].reshape(1,50,100,3))

In [62]:
yp_pred[:10]

array([[ 1.]], dtype=float32)

In [57]:
yp_pred[0][0]

1.0

In [5]:
## LOAD TEST IMAGE

from keras.models import model_from_json
import os
import glob
from PIL import Image
import numpy as np
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from matplotlib import image
from matplotlib import pyplot
im = Image.open("usimages/usimages/car-14.png")
im = im.resize((512,512))
#im = im.crop((180,155,280 , 197))
#im = im.resize((100,50))
data = np.asarray(im).copy()

#pyplot.imshow(data)
#pyplot.show()

In [59]:
206,431,739 , 601

In [45]:
model.predict(data.reshape(1,50,100,3))

array([[  5.47618950e-10]], dtype=float32)

In [6]:
###RUN SLIDING WINDOW

def sliding_window(im , w , h , stride):
    M = im.size[1]
    N = im.size[0]
    ans = []
    i = 0
    while i < (M - h + 1):
        print(i)
        j = 0
        
        while j < (N - w + 1):
            conf  = loaded_model.predict(np.asarray(im.crop((j,i,j+w,i+h)).resize((100,50))).reshape(1,50,100,3))
            if conf > 0.98 :
                ans.append((i,j,i+h,j+w))
                
            j+=stride
                
        i+=stride
    return ans
ans  = sliding_window(im , 200 , 67 , 10)


0
10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440


In [7]:
#### OUTPUT
for rr in ans:
    data[rr[0]:rr[2],rr[1]-1:rr[1]+1 , :] = [255.0 , 0.0 , 0.0]
    data[rr[0]:rr[2],rr[3]-1:rr[3]+1 , :] = [255.0 , 0.0 , 0.0]
    
    data[rr[0]-1:rr[0]+1,rr[1]:rr[3] , :] = [255.0 ,0.0 , 0.0]
    data[rr[2]-1:rr[2]+1,rr[1]:rr[3] , :] = [255.0,0.0,0.0]
    
pyplot.imshow(data)
pyplot.show()

In [24]:
lis = np.array([0])
lisy = np.array([0])

In [32]:
#### VISUALIZATION###
from keras import models
layer_outputs = [layer.output for layer in loaded_model.layers[:9]]
activation_model = models.Model(inputs=loaded_model.input, outputs=layer_outputs)

im = Image.open("usimages/usimages/car-10.png")
im = im.resize((512,512))
im = im.crop((180,155,280 , 197))
im = im.resize((100,50))
data = np.asarray(im).copy()
data = data.reshape(1,50,100,3)
activations = activation_model.predict(data)


In [33]:
from matplotlib import pyplot as plt
layer_names = []
for layer in loaded_model.layers[:9]:
    layer_names.append(layer.name) # Names of the layers, so you can have them as part of your plot
    
images_per_row = 16

for layer_name, layer_activation in zip(layer_names, activations): # Displays the feature maps
    n_features = layer_activation.shape[-1] # Number of features in the feature map
    size = layer_activation.shape[1]#The feature map has shape (1, size, size, n_features).
    size2 = layer_activation.shape[2]
    n_cols = n_features // images_per_row # Tiles the activation channels in this matrix
    display_grid = np.zeros((size * n_cols, images_per_row * size2))
    for col in range(n_cols): # Tiles each filter into a big horizontal grid
        for row in range(images_per_row):
            channel_image = layer_activation[0,
                                             :, :,
                                             col * images_per_row + row]
            channel_image -= channel_image.mean() # Post-processes the feature to make it visually palatable
            channel_image /= channel_image.std()
            channel_image *= 64
            channel_image += 128
            channel_image = np.clip(channel_image, 0, 255).astype('uint8')
            display_grid[col * size : (col + 1) * size, # Displays the grid
                         row * size2 : (row + 1) * size2] = channel_image
    scale = 1. / size
    plt.figure(figsize=(scale * display_grid.shape[1],
                        scale * display_grid.shape[0]))
    plt.title(layer_name)
    plt.grid(False)
    plt.imshow(display_grid, aspect='auto', cmap='viridis')
    plt.show()